version: "3.8"

services:
  backend:
    image: node:16-alpine
    volumes:
      - ./backend:/root/backend
    entrypoint: sh /root/backend/start.sh
  frontend:
    build:
      context: ./deploy
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/build:/var/www/html
      - ./deploy/default.conf:/etc/nginx/sites-available/default
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - backend
