version: "3.7"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: bcdb/builder:0.0.1
    container_name: bcdb-container
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app/src
      - ./public:/usr/src/app/public
      - .env:/usr/src/app/.env
    command: npm run start
